<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="registration.aspx.cs" Inherits="practicework.form.registration" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            REGISTRATION FORM<br />
            <br />        

            FirstName :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="firstname" runat="server" autocomplete="off"></asp:TextBox>
            <asp:RequiredFieldValidator ID="fname" runat="server" ControlToValidate="firstname" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />
            LastName :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="lastname" runat="server" autocomplete="off"></asp:TextBox>

            &nbsp;<asp:RequiredFieldValidator ID="lname" runat="server" ControlToValidate="lastname" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <asp:CompareValidator ID="CompareValidator1" runat="server" ControlToCompare="firstname" ControlToValidate="lastname" ErrorMessage="Cannot be same as First name" ForeColor="Red" Operator="NotEqual"></asp:CompareValidator>
            <br />
            <br />
            Age :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="age" runat="server" TextMode="Number" autocomplete="off" ></asp:TextBox>
            <asp:RequiredFieldValidator ID="eage" runat="server" ControlToValidate="age" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />

            EmployeeId :&nbsp;
            <asp:TextBox ID="employeeid" runat="server" autocomplete="off"></asp:TextBox>
            &nbsp;<asp:RequiredFieldValidator ID="eid" runat="server" ControlToValidate="employeeid" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />

            City :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="city" runat="server" autocomplete="off"></asp:TextBox>
            <asp:RequiredFieldValidator ID="ecity" runat="server" ControlToValidate="city" ErrorMessage="*" ForeColor="Red"></asp:RequiredFieldValidator>
            <br />
            <br />
            <br />

&nbsp;&nbsp;&nbsp;
            <asp:Button ID="save" runat="server" Text="SAVE" Width="89px" Height="25px" class="btn btn-dark" OnClick="save_Click" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="view" runat="server" Text="VIEW" Width="89px" Height="25px" class="btn btn-dark"  OnClick="view_Click" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div><br>
      
        <br />
        <br />
        <asp:GridView ID="data" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>
        <br />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:TrainingDBConnectionString %>" 
            SelectCommand="SELECT * FROM registration"
            DeleteCommand="DELETE * FROM registration WHERE [employeeid]=@employeeid"
            ></asp:SqlDataSource>

        <br />
        <br />
        
    </form>
</body>
</html>
